name: Docker Build and Push

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/palindrome .
          docker push $DOCKER_USERNAME/palindrome
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
